### ISSUE TITLE
TypeError: Cannot read property 'cloneNode' of undefined

### ISSUE THREAD

**Issue by ynhhoJ** [rlemaigre/Easy-DnD#1]
On DnD in console log appears error: ``TypeError: Cannot read property 'cloneNode' of undefined`` and ``Error in nextTick: "TypeError: Cannot read property 'cloneNode' of undefined"``.

**Comment by Flashantik** [comment]
> On DnD in console log appears error: `TypeError: Cannot read property 'cloneNode' of undefined` and `Error in nextTick: "TypeError: Cannot read property 'cloneNode' of undefined"`.
The same problem. Did you find a solution?

**Comment by rlemaigre** [comment]
Sorry, can't reproduce. Can you provide a small github repo or a codesandbox or anything that can help me fix this ?

**Comment by Flashantik** [comment]
> Sorry, can't reproduce. Can you provide a small github repo or a codesandbox or anything that can help me fix this ?

Well, i create a codesandbox, but everything works fine in it. It's crazy..
In my project i have that error
![image](https://user-images.githubusercontent.com/25429994/78364930-f99cd200-75c6-11ea-9e1d-c07ec3372b52.png)
I use Nuxt.js but I don’t think he’s to blame..
and link to   ```
DropList.prototype.computeInsertingGrid = function computeInsertingGrid () {
        var feedbackParent = this.$refs['feedback']['$el'];
        var feedback = feedbackParent.children[0];
        var clone = feedback.cloneNode(true);   //<----  ERROR
        var tg = this.$refs['tg']['$el'];
        tg.append(clone);
        var grid = new Grid(tg.children);
        clone.remove();
        return grid;
    };
```

My code 

```
<drag key="i" :data="data.item" class="item">
      {{data.item.name }}
</drag>
```
What could be the problem?

**Comment by rlemaigre** [comment]
If you're using a drop list, can I see the template where it appears ?

If a codesandbox doesn't work, can you make a small repo on github that I can clone ?

**Comment by dmnWebDesign** [comment]
Hi, I have something similar. Appears when we don't add any slots in DropList. Example in the link below.

https://codesandbox.io/s/easy-dnd-demo-wi84r

**Comment by rlemaigre** [comment]
To anyone stumbling upon this issue, make sure you define the "feedback" slot when using a drop list.
