### ISSUE TITLE
Drag image offset in scrolled browser

### ISSUE THREAD

**Issue by KlausVillinger** [rlemaigre/Easy-DnD#10]
When using easy-dnd in a scrolled browser window, the drag image isn't positioned at the mouse cursor, but offset by the scrolled distance (screenshot 1).
![1_dragimage_shifted](https://user-images.githubusercontent.com/11071452/78674613-282aed80-78e4-11ea-85a3-38b41f043925.png)

I played around a bit and found a works-for-me solution: when changing the startDrag-function to:
...
    this.position = {
        x: event.pageX - window.scrollX,
        y: event.pageY - window.scrollY
    };
...
everything works fine, even when scrolling while dragging (screenshot 2).
![2_dragimage_at_mousecursor](https://user-images.githubusercontent.com/11071452/78674637-32e58280-78e4-11ea-99b1-cb8ec06de0d1.png)

Can that change be incorporated or does that break any other functions?

**Comment by rlemaigre** [comment]
Sorry, this should be fixed in 1.5.1. It is on NPM.
