### ISSUE TITLE
Unexpected behavior for touch at 1.21 version (1.19 version is OK)

### ISSUE THREAD

**Issue by kidaww** [rlemaigre/Easy-DnD#102]
OS: iOS 15
Browser: Safari 

Touch (like click) on drag element child works only on padding area in iOS Safari =\

Think, following preventDefault must be provided by some props option or fixed any other way

#101 
![image](https://user-images.githubusercontent.com/26406732/149020549-86dc2371-6530-442f-80d9-b2d21d362359.png)

**Comment by nicholaszuccarelli** [comment]
Could you please provide a sample codepen project with the error? Thanks

**Comment by kidaww** [comment]
Enable responsive mode at Chrome or Safari (or mb any other browser with responsive mode firing touch events) and try to tap circles

[https://codesandbox.io/s/icy-tdd-uvuuh?file=/src/App.vue](url)

**Comment by nicholaszuccarelli** [comment]
The project link you supplied does not contain any vue-dnd assets.

**Comment by kidaww** [comment]
Sorry, try this one
https://codesandbox.io/s/elastic-chaplygin-x2p1m?file=/src/App.vue

**Comment by nicholaszuccarelli** [comment]
Thanks :) I'll take a look at this today.
I am also experiencing problems on my local project with that same line of code.

**Comment by nicholaszuccarelli** [comment]
Fix has been applied in https://github.com/rlemaigre/Easy-DnD/pull/103

Should be live soon :)
