### ISSUE TITLE
Drag @cut captures native event

### ISSUE THREAD

**Issue by loomchild** [rlemaigre/Easy-DnD#109]
I have added `@cut` event handler to a `<drag>` component inside `<drag-list>` component to allow moving elements between lists. Everything works correctly, but I noticed that if the user selects any element on the list and presses Ctri-X, then the native `cut` event is triggered, and the element is removed. This can be pretty confusing, and I don't think it's desired behavior. In my case, users can edit text in each element, and accidentally deleted the elements themselves instead of text. I managed to disable this behavior by manually ignoring native `cut` event:

```
if (event.type === 'cut') {
  return
}
```

Please let me know if you want me to prepare a quick demo code. I can also suggest a PR based on the above if you agree it's an issue.

**Comment by nicholaszuccarelli** [comment]
Please prepare a codepen demo, cheers :)

**Comment by loomchild** [comment]
Sure, here you go:
https://codesandbox.io/s/example-1-forked-fgfql3

When you enter some text into one of the boxes and try to delete it by pressing Ctrl-X, then the entire box is deleted instead of just the selected text.

If you change the `@cut` method to `onCut2` it works as expected, since the native cut event is ignored.

BTW, I realize it's a small detail, but I had a user complaining about it, and it wasn't trivial to figure out what is going on. Therefore, I am wondering if this behavior is worth changing or documenting.

**Comment by loomchild** [comment]
Actually, I found a better solution from the initial one. I can just prevent `@cut` event bubbling via `@cut.stop` on the textarea (updated the example). I think there's nothing to do in Easy-DnD, unless you'd like to document it.
