### ISSUE TITLE
how to do drag select (dragging over multiple elements to select them)

### ISSUE THREAD

**Issue by zcaudate** [rlemaigre/Easy-DnD#11]
I read the [linked article](https://www.quirksmode.org/blog/archives/2009/09/the_html5_drag.html) and looked at the examples. I'm curious if the library supports drag-selects and if so, how might one go about doing it.

**Comment by zcaudate** [comment]
something like this: https://xubaifucode.github.io/vue-drag-selector/example/demo.html

**Comment by rlemaigre** [comment]
No this library doesn't support that. The purpose of this library is to move data around. Not selecting things. On mousedown on a drag component, its data is captured. On mouseup on a drop component, the data is delivered. It's nothing more than that.
