### ISSUE TITLE
Need to access to 'native event' data on events 

### ISSUE THREAD

**Issue by scramatte** [rlemaigre/Easy-DnD#12]
Hello,

I need to access to 'native event' data on events.
standard event like "click" allow to use parameters on callback and $event variable 
to send standard event to callback.

I'm unable to achieve it with DND events. 

Can you give me an hand?

**Comment by rlemaigre** [comment]
Will look into it. It shouldn't be hard to include the native mouse event into my own events. Currently only the mouse position is exposed.

**Comment by rlemaigre** [comment]
In 1.6.0 events now have a "native" property that contains the native mouse/touch event. Can be mousedown/touchstart, mousemove/touchmove or mouseup/touchend. Can you please test this and tell me if that's what you wanted ?
