### ISSUE TITLE
Mouse Move changes causing issues

### ISSUE THREAD

**Issue by peterjslater** [rlemaigre/Easy-DnD#13]
Hi

I have a setup that was working with version 1.3.17 but no longer works with 1.5.2

Inside the drop component I am using a different component 'vue-responsive-dash' dashboard that processes mouse move events.

However after the update to 1.5.2 it appears the  dashboard component  is no longer getting mouse move events while the item is being dragged in the drop zone with the left mouse down.

I noticed you have changed from using mouse enter / leave to mouse move messages. 
Is it possible the mouse move events are not getting passed to child components.

I have replicated the issue here.
[https://codesandbox.io/s/vue-responsive-dash-051ng?file=/package.json](https://codesandbox.io/s/vue-responsive-dash-051ng?file=/package.json)

If you drag the item at the top into the dropzone, and keep the mouse down you can see the box moves around with the mouse. (using "vue-easy-dnd": "1.3.17")

However if you change the package to be "vue-easy-dnd": "1.5.2"
When you drag the item the box doesnt move around anymore, like the dashboard is not getting the mouse move events.

Any ideas ?

Regards
Peter

**Comment by rlemaigre** [comment]
Not sure if that's the problem here, but since my change from mouseenter/mouseleave to mousemove, once a mousemove event hits a drop component, it doesn't bubble further up the DOM tree anymore. I'm currently working on supporting touch devices and this problem should be fixed as a side effect.

**Comment by rlemaigre** [comment]
Can you please test this with 1.6.0 ?

**Comment by peterjslater** [comment]
Looks like new version fixed it, thanks.
