### ISSUE TITLE
Drag items prevent scroll on mobile, even if there is a `delay` set on the drag items

### ISSUE THREAD

**Issue by matthew-dean** [rlemaigre/Easy-DnD#137]
As the description says, I have draggable cards in a scrollable dialog. I found that scrolling is effectively broken because the cards take up the full width of the scrollable view.

To try to fix this, I placed a delay so that regular touchmoves would just be interpreted as scrolling. Unfortunately, it still prevented scrolling.

**Comment by nicholaszuccarelli** [comment]
Hi Matthew. Something would be incorrectly set up in your code. The `delay` does correctly work on mobile to allow for scrolling a dialog. In my app I've set the `delay` to `150` etc and that seems to work as expected.
