### ISSUE TITLE
Cannot read property 'childElementCount' of undefined

### ISSUE THREAD

**Issue by Armaldio** [rlemaigre/Easy-DnD#14]
![image](https://user-images.githubusercontent.com/3089715/79570681-33d39c80-80ba-11ea-9bfb-e8219568fd84.png)

The bug happen as soon I drag an element

What I can tell so far:
- Without drag-image slot, no errors
- With empty and filled drag-image slot, errors
- I have a tag prop on the drag element, without it works fine

Conclusion tag + #drag-image = error

Can't reproduce on codepen, might be my setup
Any tips from where i could come from ?

**Comment by Armaldio** [comment]
Ok, there you go: https://codesandbox.io/s/example-2-kb9hz?file=/src/App.vue
It's because the I'm using a `tag` and no direct child inside `<Drag>`

**Comment by rlemaigre** [comment]
When you're using the tag prop with component X, component X must support children. Try adding <slot/> somewhere in the template of component X and tell me if it works any better please.

**Comment by Armaldio** [comment]
Oh, interesting, that make sense
I'll try that
