### ISSUE TITLE
Could nice to add a git tag of version 2.1.3

### ISSUE THREAD

**Issue by hw207165** [rlemaigre/Easy-DnD#142]
Hello，could add a git tag of version 2.1.3.

Because following our company's work flow, if we need to use it，we need the download url of the source code. just like git tag specified to one version.

**Comment by nicholaszuccarelli** [comment]
@rlemaigre I can't create a tag on the GitHub project for some reason. Might need you to intervene here.

**Comment by rlemaigre** [comment]
@nicholaszuccarelli I don't know what to do short of transferring ownership to you. I can't find anything in the settings to manage permissions of collaborators as this is a personal repository or something (as opposed to an organisation).

But I couldn't find a mention on the web that creating tags is forbidden by default for collaborators. Make sure your tag name follow these rules : https://docs.github.com/en/get-started/using-git/dealing-with-special-characters-in-branch-and-tag-names . Other than that, I don't know what to do.

**Comment by rlemaigre** [comment]
But perhaps I don't understand what you want to do. What do you mean "a tag on the GitHub project" ? One of these ? Sorry if I'm being silly :-( 

![image](https://github.com/rlemaigre/Easy-DnD/assets/35061496/d58f7e0a-0bec-46da-8789-365b73670d6c)

**Comment by rlemaigre** [comment]
If you mean creating a "release", it should be possible : https://docs.github.com/en/repositories/releasing-projects-on-github/managing-releases-in-a-repository

![image](https://github.com/rlemaigre/Easy-DnD/assets/35061496/3fc352c9-eac6-414d-a51c-907be42567ba)

Do you see this on the project main page ? "create a new release"

![image](https://github.com/rlemaigre/Easy-DnD/assets/35061496/b8b19784-97d4-43e3-9232-314fd73e0d09)

**Comment by nicholaszuccarelli** [comment]
Hey, yes a release. It wouldn't let me create a release though because it needed a "tag" - but I couldn't create one. Not sure if its just a Github glitch.
![image](https://github.com/rlemaigre/Easy-DnD/assets/13761766/b0f0308b-c8f7-48b9-91d1-8cc8ed1ad215)

**Comment by hw207165** [comment]
@nicholaszuccarelli @rlemaigre 
Hello，I just need a git tag, no need to release
![image](https://github.com/rlemaigre/Easy-DnD/assets/140615995/0f3ff263-e0f9-49e0-84ca-3c076301ca31)

**Comment by nicholaszuccarelli** [comment]
That worked :)
Pushed a tag with v2.1.3 @hw207165

**Comment by hw207165** [comment]
> That worked :) Pushed a tag with v2.1.3 @hw207165

Thanks a lot
