### ISSUE TITLE
can not drop again with drop-list

### ISSUE THREAD

**Issue by peijianbo** [rlemaigre/Easy-DnD#143]
it  not allow drop the same element '4' to dorpList,how can i drop same element again to dropList?

![image](https://github.com/rlemaigre/Easy-DnD/assets/42259444/7d715d77-0ac5-49ff-a92a-f8523715f165)

**Comment by rlemaigre** [comment]
You can't, keys in Vue must be unique, and the code (in a hacky way if I remember correctly) prevents you from arriving at that situation by drag and drop.

**Comment by peijianbo** [comment]
@rlemaigre ok, thanks.
