### ISSUE TITLE
In Safari drag is triggered when option selected in select input field

### ISSUE THREAD

**Issue by ifedotov** [rlemaigre/Easy-DnD#146]
In Safari on Mac OS when there is a select input in the drag element when selecting a value the drag is triggered
https://codesandbox.io/s/example-1-forked-q2h8pz?file=/src/App.vue

**Comment by nicholaszuccarelli** [comment]
Limited support is provided for Vue 2 now.
Please attempt replication with Vue 3. However with your code snippet, it is not Safari related - happening on Chrome for me too.
Could there be an event handler you can bind to the <select> which prevents default action being chained?
