### ISSUE TITLE
Is it still being maintained?

### ISSUE THREAD

**Issue by philippkuehn** [rlemaigre/Easy-DnD#147]
No stress, I'm just looking for a fitting dnd library and easy-dnd looks very promising. However, I have already found a few bugs and I wonder if it will be maintained at all. Still, great work anyway! ✌️

**Comment by rlemaigre** [comment]
I no longer maintain it myself anymore and it has been that way for a long time. If any work is still being done on this, it would be by @nicholaszuccarelli . I do not know what are his plans regarding this project.

**Comment by nicholaszuccarelli** [comment]
I currently don't have much free time to actively attend to issues on here. 
In regards to the issues you have reported, I would recommend attempting to use the package in an actual project - I have implemented it onto an advanced form editor system and it works flawlessly.

Pull requests are appreciated :)

**Comment by philippkuehn** [comment]
Thank you for your feedback! I’m already using it in a project and have therefore created these minimal bug repros. During debugging it turned out that both issues are due to the edgescroller. I will see if I can create a PR if I find a solution.
