### ISSUE TITLE
Drag between lists

### ISSUE THREAD

**Issue by Nisgrak** [rlemaigre/Easy-DnD#15]
Hi!

Its possible drag between two or more lists? I see the example that its from a drag to a drop-list, but I want can drag bewteen the lists.

For context, I try to make a solitarie.

Thanks and amazing lib!

**Comment by rlemaigre** [comment]
If you have two drop lists, and the items of those drop lists and drag components, then you can drag between the lists. Is that not what you're looking for ?

**Comment by Nisgrak** [comment]
Okey, I try and works, it's possible to disallow the reorder?

I try to didn't set reorder event but the page get buged, and if I set to empty function it's make the animation yet.

**Comment by rlemaigre** [comment]
You did it right, the way to disallow reorder is to simply omit "@reorder=...".

But I just tried it locally and you're right, it seems it causes an infinite loop somewhere...looking into it.

**Comment by rlemaigre** [comment]
It should be fixed in 1.6.1

**Comment by Nisgrak** [comment]
Thanks! Btw, readme doesn't have install instructions, not even the name of the package or link for npm. Thats would be a nice change 😄
