### ISSUE TITLE
Is there any Vue3 demo, the main page links are all for Vue2

### ISSUE THREAD

**Issue by wilsonwu** [rlemaigre/Easy-DnD#152]

**Comment by wilsonwu** [comment]
Seems the best choose is: vue-draggable-plus

**Comment by rlemaigre** [comment]
A colleague of mine used this library successfully a few days ago in a Vue 3 project with no trouble. The API of the Vue 3 version is close, if not exactly the same, to what it was in Vue 2. This lib is still relevant I believe despite the apparent lack of Vue 3 examples, which is unfortunate but probably won't change any time soon.
