### ISSUE TITLE
Error without feedback template in list

### ISSUE THREAD

**Issue by Nisgrak** [rlemaigre/Easy-DnD#16]
I create 2 list without the feedback template(I dont want that it shows) and getting an error.
The error it's the same as in #1, maybe related.

https://codesandbox.io/s/error-without-feedback-jevl5?file=/src/App.vue

**Comment by rlemaigre** [comment]
I'll take a look at this tomorrow but you have to define the feedback slot,
always. There is a good reason for it and I don't think I can change that
easily. You can make it invisible with css if you wish though.

But I can't imagine a use case for not showing any feedback telling the
user where the new item is going to be inserted. Or perhaps the point of
insertion is not related to where mouse is when the drop occurs ? If that
is so, you don't need drop lists. Just wrap your v-for generated items in a
simple drop component.

Le mar. 21 avr. 2020 à 00:35, Eneko Rodríguez <notifications@github.com> a
écrit :

**Comment by Nisgrak** [comment]
I try to make a solitarie, so didn't want to give a feedback. Anyway give options is always nice 😄

**Comment by rlemaigre** [comment]
Did you try the solution I posted above ?

That is, use a single drop component that wraps a simple v-for list of items, instead of a drop list.

Did it work ? If so, can I close this issue ?

**Comment by Nisgrak** [comment]
I use a empty div and it works, but maybe I try the drop component yeah...

Thanks!

**Comment by matthew-dean** [comment]
>  I can't imagine a use case for not showing any feedback telling the
user where the new item is going to be inserted.

If a list is only going to be re-ordered, then I don't understand this. There's no valid insert event, so no reason to need this template.
