### ISSUE TITLE
:tag prop have wrong accepted types

### ISSUE THREAD

**Issue by Armaldio** [rlemaigre/Easy-DnD#19]
Reproduction: https://codesandbox.io/s/easy-dnd-demo-rr0qe?file=/src/App.vue

On the reprodcution you can see prop type error for the `tag` prop
On my project (can't exactly reproduce on codesandbox), I'm passing it the same way but the value is a function (Nuxt SPA mode)

Inside the component (https://github.com/rlemaigre/Easy-DnD/blob/master/lib/src/components/DropList.vue#L54), `tag` accept String and Object but should also accept Function

**Comment by rlemaigre** [comment]
I made the change for Drag, Drop and DropMask.

However, what you're trying to do won't work with DropLists. They use a Vue transition-group as root, and unfortunately transition-groups only accept standard HTML elements as tag, not Vue components.

I changed to type of the tag property to String only for DropList.

**Comment by Armaldio** [comment]
What if I don't care about having a transition ?

**Comment by rlemaigre** [comment]
I've added the no-animations prop on DropList. If that prop is true, the root of the template is a div (default) or a custom tag. In that case, the custom tag can now be a Vue component. It's in 1.7.0.

I updated your sandbox : https://codesandbox.io/s/easy-dnd-demo-fyriu?file=/src/App.vue

However, the code that prevents duplicate keys in drop lists is now broken. I'll have to look into that but no time for now

**Comment by Armaldio** [comment]
Thanks a lot
I'll try that

Looking forward to the duplicate key fix

**Comment by nicholaszuccarelli** [comment]
I am closing this issue as the `no-animations` prop has fixed the `tag` problem (as mentioned above^).
In regards to the duplicate key problem, I have been unable to replicate the issue being discussed (and I would expect it is up to you to ensure that no keys are being duplicated when rendering DropLists).
Feel free to comment if there is another underlying issue that I have missed.
