### ISSUE TITLE
Add class to closest Drop component

### ISSUE THREAD

**Issue by lesharris** [rlemaigre/Easy-DnD#22]
It would be very useful if during dragging the library could add a class to the closest Drop component based upon current mouse position.  This would enable the use of invisible Drop targets which become visible when the drag object is close to them.

An example use-case is for linear drop targets that act as spacers between elements that would be invisible in normal situations but provide clear feedback to the user in insertion operations.

Lastly, this is a very nice library, thank you for your work - it fills a hole for vue drag and drop libraries that get out of your way and don't assume structure.

**Comment by lesharris** [comment]
A visual example of the behavior I want this functionality for:

![Example](https://i.imgur.com/J8kfBkk.gif)

**Comment by Armaldio** [comment]
Hey, 

This is already possible. See this comment https://github.com/rlemaigre/Easy-DnD/issues/9#issuecomment-613593051

Something like this should work:

- Inside DropList:
```html
    <template #feedback="{ data }">
      <div
        :key="data.key"
        class="item feedback"
      />
    </template>
```

```css
.item.feedback {
    flex: 0 0 0;
    align-self: stretch;
    outline: 2px solid rgb(108, 122, 255);
    z-index: 4;
  }
```

**Comment by lesharris** [comment]
Thanks @Armaldio It'd be nice if a DropList wasn't required but that will work fine!
