### ISSUE TITLE
"Cannot read property 'dispatchEvent' of null" when going offscreen

### ISSUE THREAD

**Issue by FIFARenderZ** [rlemaigre/Easy-DnD#24]
`Uncaught TypeError: Cannot read property 'dispatchEvent' of null at HTMLDocument.onMouseMove (vue-easy-dnd.esm.js?fdcb:331)`

This happens whenever a user drags a drag element off-screen. Should be an easy fix tho

EDIT: This only happens on mobile devices (aka touchscreens)

**Comment by rlemaigre** [comment]
Fixed in 1.9.4
