### ISSUE TITLE
Cannot drag from drop list to drop.

### ISSUE THREAD

**Issue by rahala9** [rlemaigre/Easy-DnD#27]
I get a null object for the event data when trying to drag from a drop-list to a drop. The use case for this is I would like to be able to drag from a drop-list to a drop to then delete from the drop list while still being able to drop from a different data table into the drop list. Any way around this?

**Comment by rlemaigre** [comment]
It should work.

Can you provide me with a sample of the problem please ? Just fork one of the sandboxes in the readme and start from there.
