### ISSUE TITLE
DropList should inheritAttrs: false

### ISSUE THREAD

**Issue by Armaldio** [rlemaigre/Easy-DnD#28]
![image](https://user-images.githubusercontent.com/3089715/83396868-ed819500-a3fc-11ea-8a06-0b311682ec0d.png)
![image](https://user-images.githubusercontent.com/3089715/83396994-30436d00-a3fd-11ea-9a46-6dff69e4b813.png)

**Comment by rlemaigre** [comment]
fixed in 1.9.3
