### ISSUE TITLE
Drag image not always on top (z-index)

### ISSUE THREAD

**Issue by ddenev** [rlemaigre/Easy-DnD#31]
The README says (https://github.com/rlemaigre/Easy-DnD#drag-image):

> Easy-DnD makes it so that this image is always on top of everything else.

This is not always the case. Currently the `z-index` for the drag image is set to 1000 (`createDragImage()` in `createDragImage.ts`) which is not always above everything else.

Is there a way to manually set the `z-index` for the drag image for the cases when 1000 is not sufficient?

**Comment by rlemaigre** [comment]
I suppose I could use the maximum possible value for z-index instead of 1000.

In the meantime, does this fix work ?
```html
<body>
<div style="z-index:1">
... your content...
</div>
</body>
```

**Comment by ddenev** [comment]
> In the meantime, does this fix work ?

If what you are suggesting (it's not completely clear to me) is to manually set `z-index` for the drag image then I am not sure that it would work since in `createDragImage.ts` you are setting `z-index` as an inline style as well:

```
export function createDragImage(el: HTMLElement): HTMLElement {
    let clone = deepClone(el);
    clone.style.position = 'fixed';
    clone.style.margin = '0';
    clone.style["z-index"] = '1000';
    clone.style.transition = 'opacity 0.2s';
    return clone;
}
```
so I guess my setting will be overriden.

**Comment by rlemaigre** [comment]
No. What I mean is to wrap all your content (your whole app) inside a div with z-index 1 (or whatever, but less than 1000...the div must also be positioned, forgot to mention that in my previous post). So when a drag image appears, the DOM will look like this :
```html
<body>
<div style="z-index:1; position: relative;">
... your whole application...
</div>
<div style="z-index: 1000; position: fixed; ...">...drag image...</div>
</body>
```
...and it should work, even if there are things with z-index > 1000 in your application.

Z-index values are not absolute. You need to understand what is a stacking context to property use them. See for exemple https://philipwalton.com/articles/what-no-one-told-you-about-z-index/

**Comment by ddenev** [comment]
Ah, yes, now I get it, thank you for explaining! Yes, that would definitely work.

I don't think there is a need to increase the current `z-index` in Easy-DnD, the above approach solves my problem.

Thank you again for your time!
