### ISSUE TITLE
Allow drag and drop on certain div / icon only. 

### ISSUE THREAD

**Issue by IT-iddiot** [rlemaigre/Easy-DnD#32]
Hi. 

How can I restrict the drag and drop on certain div only? One of the examples will be handle in vue-draggable. 
[https://sortablejs.github.io/Vue.Draggable/#/handle](https://sortablejs.github.io/Vue.Draggable/#/handle)

I am a big fan of Easy-DnD. Hopefully, this feature can be added also.

**Comment by rlemaigre** [comment]
It is already implemented, but not documented yet, sorry. It is the handle prop on Drag components. You pass it a CSS selector that targets the handle. See https://github.com/rlemaigre/Easy-DnD/blob/master/src/App6.vue for an example of this.
