### ISSUE TITLE
Error when accessing data in drag-image slot

### ISSUE THREAD

**Issue by mike85** [rlemaigre/Easy-DnD#33]
When accessing the {{data}} prop within the drag-image slot it’ll give an error.

```
<template v-slot:drag-image="{data}">
    <div>
        <p>{{data.length}}</p>
    </div>
</template>
```

In an earlier Version 1.2 as used in the [example](https://codesandbox.io/s/easy-dnd-demo-2-xnqbz) it’s working.

**Comment by mike85** [comment]
Is the problem that drag-image on Drag does not support props anymore?

**Comment by rlemaigre** [comment]
Yes I removed the type and data props from the drag-image slot on Drag components (and only on Drag components). It was useless because the type and data is already available in the scope of the drag-image slot (for Drag components). I updated the example, sorry about that.

```html
<drag :data="x">
  <template v-slot:drag-image>
    <div>
        <p>{{x}}</p> <!-- x is already available here, no need to pass it as prop -->
    </div>
  </template>
</drag>
```
