### ISSUE TITLE
Option to remove DropList default content wrapper

### ISSUE THREAD

**Issue by danieldilly** [rlemaigre/Easy-DnD#36]
Hi.  I'm using your component and so far it's been a pleasure to work with.

I'm having an issue when using the `DropList` component with a table and rows.  I'm using the `DropList` with the `tag` set to `tbody`.  If there are no `items` available, I would like to display an empty row (`<tr>`).  The problem is that the default slot for `DropList` is wrapped in a `div` container:  `<div key="drop-list-content"></div>`.  As a result, my `tr` is within a `div` within the `tbody` and therefore does not display.

I can somewhat get around this by using the `template` tag instead of a `tr` and then targeting `tbody>div` and setting `display: table-row` but it would be much better if the `DropList` had the option to disable this `div` wrapper or if there was another slot (without a wrapper) to display content when there are no `items`.

I hope you can get around to updating this.  In the meantime I'll just hack around it.  Thanks for making this library!

**Comment by nicholaszuccarelli** [comment]
This has been resolved in v1.15.0.
The default slot content is a direct relative to the DropList component. Remember to define a key for each direct element inside the slot :)

Please close @rlemaigre
