### ISSUE TITLE
Drag handle

### ISSUE THREAD

**Issue by Armaldio** [rlemaigre/Easy-DnD#4]
Is there a way to have a drag handle (sub only sub element is draggable) ?

**Comment by rlemaigre** [comment]
Sorry, not yet.

**Comment by Armaldio** [comment]
Would it be hard to do it ?
Might contribute

**Comment by rlemaigre** [comment]
No it shouldn't be hard.

A mousedown event on a Drag component is what initiates a drag. In the file DragMixin.ts, a listener for mousedown is bound to the whole drag component. In the case of a handle, that listener should be bound to a sub element. It should do the trick...
