### ISSUE TITLE
Inconsistent documentation about Drop classes when type is not accepted

### ISSUE THREAD

**Issue by ddenev** [rlemaigre/Easy-DnD#41]
The "Types" section (https://github.com/rlemaigre/Easy-DnD#types) says:

> As far as Easy-DnD is concerned, if a Drop component doesn't accept the type of the current drag operation, it behaves like any other part of the page that is not sensitive to drag and drop. It is ignored during the drag, **_no special CSS classes are applied_**, no special cursors / drag images are displayed and no special events are triggered.

The accented part - "no special CSS classes are applied" - is not particularly correct since:
1. the "CSS classes" section (https://github.com/rlemaigre/Easy-DnD#css-classes) says:

> During a drag operation, the Drop components on the page are assigned several CSS classes :
> - for all Drop components : type-allowed if the Drop component accepts the type of the drag operation, **_type-forbidden otherwise_**

2. `type-forbidden` class is indeed applied when the type is not accepted.
3. `drop-out` class is additionally applied => this seems like a bug since the "CSS classes" section says that `drop-in` and `drop-out` are applied only when type is accepted by the Drop component.

https://codesandbox.io/s/example-3-g7io8

**Comment by nicholaszuccarelli** [comment]
Closing because the next update will fix the inconsistent documentation in regard to CSS classes. `drop-out` is meant to be applied.
