### ISSUE TITLE
[Question] I am unable to get this to work in my page builder.

### ISSUE THREAD

**Issue by dannysmc95** [rlemaigre/Easy-DnD#44]
Hey, we spoke on the Vue forum.

I tried making this work but I keep getting the following: https://github.com/rlemaigre/Easy-DnD/issues/1

I did do what one of the comments says which was to use the simple drop option which is fine, but this does not give any controls, like removing it from the previous place and hover controls to see where it will go.

So in my project, I need to drag and drop from a module list, and then the ability to move everything around within the page, so moving blocks from multiple children deep to any place required, but I was unable to get this to work in a way that was useful, I just kept getting the same error, I would also like to support the line that presents when dragging as this is much cleaner.

Any way we could collab to make this work, so I can also understand this more, as if I can get this to work in my prototype my company will most likely use it, so I just want to understand exactly how it works, as it's no where near as simple as vue-draggable which is fine, but I need to understand.

What I did was the following, I created a drop list, with a separate v-for loop inside of containers as my page builder uses a container system, where each container has it's own row and columns, allowing for much more custom designs of the layout, so there is really only one place I need to add support for the re-ordering of elements within the page, which is here and then the wrapper that wraps all normal page components, forms, lists, etc, etc.

So in my main container file, I did a drop list inside of the container row which inside of the drop list it has it's own div container that loops multiple times for each given column, then inside the column there will be another component, whether that being another container or an actual page component, regardless, I need to support moving the page component anywhere inside of other columns in other components, or to re-order the components already in a column, and then being able to move the columns, so moving them to the left or swapping two, etc.

**Comment by rlemaigre** [comment]
I was never able to reproduce the error you mention https://github.com/rlemaigre/Easy-DnD/issues/1 :-( . I closed the issue because no one mentioned it anymore so I thought one of the changes I made since had made the error go away. But it seems not.

If you can share with me a repository (as simple as possible) on Github that causes the error, I'll take a look at it.

**Comment by dannysmc95** [comment]
@rlemaigre No worries, I have given you a snapshot from a component similar to your Flex.vue example in the nested example, you can use it and put it anywhere you need. https://gist.github.com/dannysmc95/fc1ea10179a1f39cd0122a9bf8caff70 but it's faster just to give you this as you may spot some silly issues.

**Comment by rlemaigre** [comment]
It seems you didn't define the "item" slot for your drop list. When you use a drop list, you don't loop over the items yourself, instead you define the item slot and you let the drop list render the items using that slot. That way the drop list can insert feedback in between the items when a drag is in progress over the drop list.

See this example : https://codesandbox.io/s/droplist-ozs8b?file=/src/App.vue

**Comment by dannysmc95** [comment]
@rlemaigre I see, that makes sense, but I am still seeing the same error, I have updated the original gist.

**Comment by rlemaigre** [comment]
It seems ok to me now...

I'll need a working minimalist project so I can reproduce the issue.

**Comment by rlemaigre** [comment]
Wait you also need to define the feedback slot.

**Comment by dannysmc95** [comment]
So wait what is the feedback slot, is that the line thingy to say where the block should drop to?

**Comment by dannysmc95** [comment]
Also I keep getting errors about keys not being string and number, in both the feedback and item slots, is there an index that I can use? Similar to doing `v-for="(item, index) in items"`?

**Comment by rlemaigre** [comment]
> So wait what is the feedback slot, is that the line thingy to say where the block should drop to?

Yes. And you need to give it a unique key. Again, see this example : https://codesandbox.io/s/droplist-ozs8b?file=/src/App.vue

If you want it to look like a line, try for example flex: 0 0 0; align-self: strech; outline: 1px solid blue; if you're in a flex container.

**Comment by rlemaigre** [comment]
> 
> 
> Also I keep getting errors about keys not being string and number, in both the feedback and item slots, is there an index that I can use? Similar to doing `v-for="(item, index) in items"`?

Weither you're using a v-for or a drop list (which internally uses a v-for), the items must have a unique key and it must be a string or a number. Vue requires it.

**Comment by dannysmc95** [comment]
Sure, but you can get away usually with just using the index of that loop, I use it all the time instead :P.

Ahh, so we must use flex in order to use this? as I was trying to use it without but it was having a fit saying it needed a flex also note in the most recent change: https://gist.github.com/dannysmc95/fc1ea10179a1f39cd0122a9bf8caff70 this now does nothing? Like before when I did not define flexDirection and row, column it was at least throwing an error saying it.

![image](https://user-images.githubusercontent.com/5339861/89394925-95208980-d704-11ea-979c-6e9192083d3b.png)

Which was also showing me the data from the feedback slow, but now nothing is happening, since defining the direction and adding the additional attributes, nothing happens, you can drag it, but it does not _do_ anything, no feedback no change? Any ideas?

Sorry I am being a pain! :P

**Comment by dannysmc95** [comment]
FYI to the above, when I say nothing happens now, once defining the flex stuff, nothing happens, so no errors, no notices, no messages, drag works but when you hover over a drop list it just says

**Comment by rlemaigre** [comment]
When you use nested drop lists, you need to help the library by telling it what direction the items are lining up, row or column otherwise you get warnings.

Drop lists have no styling applied whatsoever, you need to take care of that. You don't _need_ to use flex, you could use inline-blocks or whatever...the layout is really up to you.

**Comment by dannysmc95** [comment]
@rlemaigre sure, but then why does it not allow me to drag? I can see some of the classes say drag-forbidden...?

**Comment by dannysmc95** [comment]
Okay so after some messing I can see that fir sine reason even though I am using the template slot, the drag element is around the all template items hence why nothing actually drags, I can see the line showing, but it won't go anywhere because the drag container is around all containers, instead of just the ones it should be.

**Comment by olasunkanmi04** [comment]
> Sure, but you can get away usually with just using the index of that loop, I use it all the time instead :P.
> 

So is there a way to use the index when I don't have a unique key?
Until data is submitted before I can get a unique id, before then, I need to be able to use the drag
