### ISSUE TITLE
Form Builder: Vue components draggable

### ISSUE THREAD

**Issue by lowercase00** [rlemaigre/Easy-DnD#46]
Hey there, thanks a lot for the library, awesome code.
I'm trying to make a form builder, much like WYSIWYG editor of the example.
A good benchmark is Jira custom issue fields, as the gif bellow:

![Untitled-Project](https://user-images.githubusercontent.com/21188280/89678907-64884d80-d8c6-11ea-81d3-8eea77014141.gif)

I could replicate the examples with no problem, but I'm having a hard time dragging components, while having the handler with a different image, what I mean is: on the right side I have the "components type" like a checkbox, a text etc. And when I drag them, they appear at the form as the component itself: the checkbox, the textbox etc. When I try to that, I would get the components' text.

Any ideas or examples that I could use? Thanks!

**Comment by rlemaigre** [comment]
I'm sorry I'm not sure I understand the problem. Can you perhaps make a codesandbox with a bare bone example that illustrate the issue ?

**Comment by kaspermarkus** [comment]
@lowercase00 Is your problem that the "preview" of the component of the form is only the components text? If so, what you need is to use the template feedback slot with the data... for example:
```
              <drop-list :items="myItems">
                 <template v-slot:feedback="{data}">
                    <myPreviewComponent :data="data"></myPreviewComponent>
                  </template>
              </drop-list>
```

where `myPreviewComponent` would be your custom component to render the preview... This would then show whenever you drag a component over the form in the place where the component would be finally rendered in the form.
