### ISSUE TITLE
Nested tree

### ISSUE THREAD

**Issue by jaronwanderley** [rlemaigre/Easy-DnD#5]
Could I create a nested tree of draggable elements, using Easy-DnD?

**Comment by rlemaigre** [comment]
Perhaps but I haven't tested the library in such a complex setting as of yet. The most complicated thing I've done so far (and it was easy) is described in this issue : https://github.com/rlemaigre/Easy-DnD/issues/7

I suspect problems will arise when it comes to re-parenting nodes.

**Comment by jaronwanderley** [comment]
thanks! I'll try... but just for fun
