### ISSUE TITLE
NuxtJS support

### ISSUE THREAD

**Issue by tomasSlouka** [rlemaigre/Easy-DnD#53]
I would like to use it in the NuxtJs project. Is it possible?

**Comment by rlemaigre** [comment]
Should be.

**Comment by tomasSlouka** [comment]
When I'm trying to use it as a plugin I get this compilation error

`"export 'default' (imported as 'VueEasyDnd') was not found in 'vue-easy-dnd'`

and when as a module i get this error

`TypeError: Module should export a function: vue-easy-dnd`

**Comment by rlemaigre** [comment]
I don't know NuxtJS. The only thing I tried is to create a nuxt app and add vue-easy-dnd to the package.json file. With version 1.10.2 it seemed to work. Should I do something else ?

**Comment by JoJuhasz** [comment]
I don't have problems with nuxtjs. Simply install component with npm install them import any dnd component you want to use inside your nuxt component since they are not autoloaded like nuxt components. And use it like in the exemples.

**Comment by rlemaigre** [comment]
@JoJuhasz Thank you for your explanation. I'm closing this.
