### ISSUE TITLE
Pre-Drag-Start event

### ISSUE THREAD

**Issue by JohnnyAW** [rlemaigre/Easy-DnD#55]
Hello, is it somehow possible to update UI right before drag event will start? 
What I try to do: I have DropList, that has components, that can be collapsed/expanded. I want to collapse my components for better dragging experience. If I update UI using dragstart - event, reordering is wrong, because it uses component sizes before the UI update.

**Comment by nicholaszuccarelli** [comment]
This is solved with the introduction of the DropList $refs.dropListRef.refresh() method which lets you recompute the grid sizes.

@rlemaigre Might want to close this.
