### ISSUE TITLE
Render Function Error

### ISSUE THREAD

**Issue by colzzky** [rlemaigre/Easy-DnD#56]
Hi

I was trying to do a render function implementation of Easy-Dnd Nested-list drag and drop (https://codesandbox.io/s/nested-drop-lists-nw605)

But I could not get it to work 100%

Here's my codepen -> https://4wuzb.csb.app/

I started recreating the Component->Flex.vue file...

But the output was different from the original

Does Easy-DnD have a special case for Render Function implementation?

**Comment by rlemaigre** [comment]
I never used render functions so I'm not sure.

I spotted a mistake in your code though : in Flex.vue, line 90 should be 
`feedback: function ({data}) {`
 instead of
`feedback: function (data) {`

There may be other mistakes.
