### ISSUE TITLE
[Vue warn]: Error in event handler for "dragtopchanged": "TypeError: Cannot read property 'childElementCount' of undefined" upon adding divs within dragTable template

### ISSUE THREAD

**Issue by maramizo** [rlemaigre/Easy-DnD#57]
Hi,
I added optional buttons to show on hover, as such:
  ```js
<template v-slot:item="{ item }">
    <drag
    tag="generic"
    :model="item"
    :key="key(item)"
    :data="item"
    @cut="remove(item)"
    @mouseover.native="startHovering(item)"
    @mouseleave.native="stopHovering(item)"
    class="relative"
    v-on:delete="deleteChild"
    >
      <div v-if="showButtons === key(item) && $edit.mode" class="absolute top-0 right-0">
        <v-btn
        class="mx-2"
        fab
        dark
        color="indigo"
        v-if="item.items && item.items.length > 0"
        >
          <v-icon dark>
          mdi-plus
          </v-icon>
        </v-btn>
        <v-btn
        class="mx-2"
        fab
        dark
        color="red"
        @click="remove(item)"
        >
          <v-icon dark>
          mdi-minus-circle
          </v-icon>
      </v-btn>
    </div>
    <template v-slot:drag-image>
      <div class="drag-image">DRAG</div>
    </template>
    </drag>
</template>
```

![image](https://user-images.githubusercontent.com/7774220/101975519-e1954c00-3c45-11eb-9226-8b023b586b25.png)
(Image just looks better, right?)

And I've noticed there's been this error, repetitively showing whenever I attempt to drag children:

`[Vue warn]: Error in event handler for "dragtopchanged": "TypeError: Cannot read property 'childElementCount' of undefined"`. 

The error does not stop the code from working and I can still do what I've set off to do, but it's just annoying to deal with.

Great job with the library, thanks a bunch.

**Comment by ionuttibi** [comment]
Having the same issue, any updates?

**Comment by danieljianu** [comment]
We're also having the exact same issue.

It appears the problem comes from the fact that `this.$refs['drag-image']` is undefined in `DragMixin.createDragImage()`.

This only happens when the `drag-image` slot is set and the `tag` prop is set to a Vue component.

```typescript
export default class DragMixin extends DragAwareMixin {
  ...
  createDragImage(selfTransform: string) {
        let image;

        if (this.$scopedSlots['drag-image']) {

            let el = this.$refs['drag-image'] as HTMLElement;

            if (el.childElementCount !== 1) {      // ❗️ This is where is crashes, since el is undefined
                image = createDragImage(el);
            } else {
                image = createDragImage(el.children.item(0) as HTMLElement);
            }
        }
        ...
  }
  ...
}
```

Please let me know if you have any information or workarounds for this, as it's pretty much blocking us right now.
Thank you!

**Comment by rlemaigre** [comment]
@danieljianu  Sorry for the late reply. When using a Vue component as tag, be sure it has a default slot (<slot/>) defined in its template. If this is indeed the problem, I'll add a note in the docs regarding this.

**Comment by danieljianu** [comment]
@rlemaigre - I can't thank you enough! 🥇
This was indeed the problem.

Kudos to you! 👍
