### ISSUE TITLE
Drop on a tree node. - how to pass the tree node item key to the @drop function

### ISSUE THREAD

**Issue by moktc** [rlemaigre/Easy-DnD#58]
I am trying to figure out how to pass the tree node item to the @drop function. 

```
                    <v-treeview :items="items">
                    <template slot="label" slot-scope="props">
                    <drop
                        @drop="onDropTree"
                        key=""
                        style="height: 100%"
                        tag="v-list"
                        three-line
                        class="my-list"
                    >
                        Drop here {{ props.item.name }}
                    </drop>
                    </template>
                </v-treeview>

```
in the example above, I like to pass the props.item.name to the onDropTree function? Any suggestion?. Thanks.

**Comment by rlemaigre** [comment]
It is my understanding that passing a function `x` to en event handler in Vue is simply a shortcut for writing the code `x($event)`. So instead of passing `onDropTree` I believe you could pass `onDropTree($event, props.item)`. That way you have access in onDropTree to both of what is being dragged and what is being dragged into.

Can you try this and tell me if this works ?

**Comment by moktc** [comment]
Thanks for your quick response. I made the change as you suggested and is happy to confirm that it works!!! See the code below.

```
 <v-treeview :items="items">
            <template slot="label" slot-scope="props">
              <drop
                  @drop="onDropTree($event, props.item.name + ' is the dropped treenode ' )"
              >
                Drop here {{ props.item.name }}
              </drop>
            </template>
          </v-treeview>

    onDropTree( event, treeNode ) {
      console.log("on DropTree TEST " + treeNode,event.data);
    },


```
