### ISSUE TITLE
Index for item slot in drop-list

### ISSUE THREAD

**Issue by giray123** [rlemaigre/Easy-DnD#59]
I need to pass the index of the element to my item component in the item slot of the drop-list. Is it possible? It seems it only has "item" and "reorder" attributes.

**Comment by VincentVanclef** [comment]
Would love to get the index from the <template v-slot:item="{item}"> drag items

**Comment by nicholaszuccarelli** [comment]
Not sure if this thread should be closed but the index is available. { item, reorder, index }
