### ISSUE TITLE
Nuxt, import error

### ISSUE THREAD

**Issue by Flashantik** [rlemaigre/Easy-DnD#6]
When using nuxt, in universal mode. When importing we get an error
> Cannot use import statement outside a module

![image](https://user-images.githubusercontent.com/25429994/78004857-656f0880-7343-11ea-8f87-e5c5c6362e12.png)

**Comment by rlemaigre** [comment]
I'm sorry I've no experience with Nuxt.

**Comment by Flashantik** [comment]
> I'm sorry I've no experience with Nuxt.

This error occurs when the code is executed on the server. Perhaps in your code somewhere there is a document / window during initialization .. By the way, is it possible to add disable mode for components?

**Comment by jschoedt** [comment]
I guess that would make it unusable and break any SSR?

**Comment by rlemaigre** [comment]
I'm willing to make any change necessary to make it work but I have no idea how. I only have a vague idea of what SSR is.

I did use "document" in some places in the code to attach listeners, can it be related to that ? What would be the fix ?

**Comment by jschoedt** [comment]
Sound good @rlemaigre . I think it would make your library more usable as it will be a show-stopper for anyone using SSR. I encourage you to read this guide: https://ssr.vuejs.org/guide/universal.html#data-reactivity-on-the-server.

In short you need to move all _window_ and _document_ using code into _beforeMount_ or _mounted_. That way it will not be called when run it on the server. Depending on your code i should not be too hard to refactor. Search for all use of  _window_ and _document_ and move it.

Keep up the good work. I would like to test it when this is fixed.

**Comment by danieldilly** [comment]
If it's not the `import` statement but the use of the components that is causing the error, try wrapping them in `<client-only></client-only>` tags.

**Comment by danieldilly** [comment]
I got this working just by running the `vue-easy-dnd.esm.js` file through a Babel REPL and taking that output and overwriting the original contents.

**Comment by rlemaigre** [comment]
It should work fine now, I tested it with Nuxt. Try version 1.10.2 or superior.

There are now three builds, an SSR build for use when running the code in Node (with none of the old "import" statements that were causing errors), an ESM build for use with bundlers like Webpack and a browser build.

Please bear with me, I'm learning about all these things as I go.
