### ISSUE TITLE
When I try to easy-dnd to my project it compiles but not load

### ISSUE THREAD

**Issue by bandarrinha** [rlemaigre/Easy-DnD#61]
When I try to easy-dnd to my project it compiles but not load, I receive the following message on browser console:

Uncaught ReferenceError: VuePropertyDecorator is not defined

![image](https://user-images.githubusercontent.com/4522563/109170443-89a7b500-775f-11eb-8633-4b76a63d196b.png)

**Comment by peng-double** [comment]
I'm sorry, I also encountered the same problem. In my Vue2 project, I used easy dnd 1.22.0. What should I do to solve it
