### ISSUE TITLE
Layout on the readme.md

### ISSUE THREAD

**Issue by ijpatricio** [rlemaigre/Easy-DnD#64]
Hello @rlemaigre 

Thank you for an awesome work!! How can I send a couple of coffees for this!??!

Also, I'm on my way to build a page layout builder, and this one in the readme is very spot on!

Any chance it is open source, or possible to find in a gist??

![image](https://user-images.githubusercontent.com/26031459/112011430-2c194500-8b20-11eb-88eb-dc50e95ed4b2.png)

**Comment by rlemaigre** [comment]
Hello, see this issue : https://github.com/rlemaigre/Easy-DnD/issues/51
