### ISSUE TITLE
drag-image slot position， if body has a scroll bar, drag image will be dislocation。

### ISSUE THREAD

**Issue by coffeew** [rlemaigre/Easy-DnD#74]
drag-image slot position， if body has a scroll bar, drag image will be dislocation。

https://user-images.githubusercontent.com/43375771/119803325-eeff7380-bf11-11eb-81c1-619f56cbf193.mp4

**Comment by rlemaigre** [comment]
Hello,

What version are you using ? In version 1.12.1 I can't reproduce the problem, see https://codesandbox.io/s/example-4-forked-y67n0
