### ISSUE TITLE
Dragging inside scrollable body fails

### ISSUE THREAD

**Issue by JCaye** [rlemaigre/Easy-DnD#90]
Any help with draggin inside a scrollable container?
sample code with the issue: https://codesandbox.io/s/multidraganddrop-multiplelists-forked-up5wk?file=/src/App.vue

Description: when dragging an item inside a scrollable container, while the scrolling itself happens nicely enough, the actual reordering action does not drop it at the arbitrary location one scrolls to. It seems to drop the item at the last available position on the list originally rendered

Expected: if I drag an item all the way to the bottom and drop it, it should be placed where I drop it.

**Comment by nicholaszuccarelli** [comment]
Hi mate, thanks for pointing this out. I'll be sure to look at this issue this week and then provide a fix. 
Certainly seems like the scrolling implementation I provided has some bugs in specific use cases.

**Comment by JCaye** [comment]
Hi nicholas! thanks for responding. After playing around, it turns out that the issue is when the overflow properties are set on the DropList element itself. Placing them in a wrapper element behaves as expeted and works for my usecase.

Btw, AWESOME drag n drop component, we've been switching around between 3 or 4 different ones and this is the best so far, by a wide margin

**Comment by nicholaszuccarelli** [comment]
Yes that was indeed the issue. Still certainly a bug though. I have fixed it for the upcoming release which should be merged within the next day or so.

The package is awesome :) I am not the original creator but I was in the same situation as you - switching between different packages, and this one was definitely the best.

**Comment by nicholaszuccarelli** [comment]
This issue has been resolved in 1.16.0

Thanks for finding it! :)
