### ISSUE TITLE
drop list nest item

### ISSUE THREAD

**Issue by EthanHung** [rlemaigre/Easy-DnD#94]
how can I create a nested item list in drop-list for "another item list"?
I would like to drop in to second list and drop to list item
![image](https://user-images.githubusercontent.com/5393725/133966720-b708eee3-35f8-43b4-a279-fa4faa31ca6e.png)

**Comment by samuel-finistere** [comment]
Hi. you need to use recursive components to achieve this.
to render an item, I use a condition: "does it support children nodes"
if yes: render a item list container
else: render my "leaf" component

**Comment by EthanHung** [comment]
> Hi. you need to use recursive components to achieve this.
> to render an item, I use a condition: "does it support children nodes"
> if yes: render a item list container
> else: render my "leaf" component
sorry I dun get it. is there any example code?
I tried to add the code at line 102

https://codesandbox.io/s/nested-drop-lists-forked-539qx?file=/src/App.vue
